---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    required_packages:
    - python3-pip
    - jq

- name: Install required python packages
  ansible.builtin.pip:
    name: "{{ required_python_packages }}"
    extra_args: --upgrade
    executable: pip3
  vars:
    required_python_packages:
    - boto
    - boto3
    - botocore
    - awscli

- name: Set the correct permissions for aws
  ansible.builtin.file:
    path: /usr/local/bin/aws
    owner: root
    group: root
    mode: '0755'

- name: Set the aws cli user
  ansible.builtin.include_tasks: user.yml
  when: aws_user is defined
...
