---
- name: Converge
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
  - name: Include andrelohmann.awscli
    ansible.builtin.include_role:
      name: "andrelohmann.awscli"
...
